 name: Get Git Log
 on: [push]
 jobs:
  runmultiplecommands:
   
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v1
      name: commads
    - run: |
       git log
       
       
      
